### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/yevgeny-zamyatin_we_gregory-zilboorg#1]
- For the bridgeheads, I think we want to sentence-case the items instead of titlecasing them. Also, bridgeheads should have ending punctuation, usually a period.

- `z3998:ordinal` doesn't need the z3998 namespace, `ordinal` is in the epub namespace (as a draft at least)

- MathML isn't necessary here, because the bulk of the work doesn't contain equations. In this case you can inline it per styles in the manual. We don't want to do mathml for incidental stuff like this, because it gets converted to PNG and so looks off in a plain-prose work.

- In the foreword, should we put the big quotation in a blockquote and remove hr?

- `(“<i epub:type="z3998:grapheme">b</i>” like a splash.)` Can we remove quotes here? We already have it italicized, and that would make it consistent with the other grapheme in the chapter.

- Chapter 8: `<i epub:type="z3998:grapheme">P</i>` I think this can be lowercased

- Long description: `facade` should be `façade`

**Comment by robinwhittleton** [comment]
OK, all of these addressed. Thanks for the detailed review :)
